locale           : "en-US"
encoding         : "utf-8"
timezone         : "Asia/Seoul"

title            : "0x00000FF"
title_separator  : " :: "

name             : "0x00000FF"
description      : "0x00000FF's private storage"

url              : "https://blog.patche.me"
baseurl          : ""

include          : [ "assets" ]
exclude          : [ "Gemfile", "Gemfile.lock", "_site" ]

kramdown:
    syntax_highlighter_opts:
        disable: true
