locale           : "en-US"
encoding         : "utf-8"
timezone         : "Asia/Seoul"

title            : "0x00000FF"
title_separator  : " :: "

name             : "0x00000FF"
description      : "a blog"

url              : "https://blog.patche.me"
baseurl          : ""
permalink        : "/post/:title"

include          : [ "assets" ]
exclude          : [ "Gemfile", "Gemfile.lock", "_site" ]

kramdown:
    syntax_highlighter_opts:
        disable: true

webrick:
    headers:
        Content-Security-Policy: default-src 'self'; img-src 'self'; style-src 'self'; script-src 'self';